# Generated by Django 3.2 on 2023-12-07 15:43

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('direccion', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_cliente',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('direccion_envio', models.TextField(null=True)),
                ('estado', models.CharField(choices=[('p', 'PAGADO'), ('s', 'SOLICITADO')], default='s', max_length=1)),
                ('nro_pedido', models.CharField(max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.cliente')),
            ],
            options={
                'db_table': 'tbl_factura',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_marca',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('sexo', models.CharField(choices=[('h', 'men'), ('c', 'children'), ('m', 'women')], default='m', max_length=1)),
                ('dimensiones', models.CharField(default='30 x 10 cm', max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pais', models.CharField(default='Perú', editable=False, max_length=100)),
                ('material', models.CharField(choices=[('o', 'oro'), ('p', 'plata'), ('c', 'cobre')], default='o', max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.marca')),
            ],
            options={
                'db_table': 'tbl_producto',
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.producto')),
            ],
            options={
                'db_table': 'tbl_factura_detalle',
            },
        ),
    ]
